// Central map of local stock assets. See public/assets/CREDITS.md.
export const ASSETS = {
  "grove-hero": "/assets/hero/grove-hero.webp",
  "grove-hero-mobile": "/assets/hero/grove-hero-mobile.webp",
  "hero-video-poster": "/assets/hero/hero-grove-aerial-poster.jpg",
  "grove-rows": "/assets/hero/grove-rows.webp",
  "coast-hero": "/assets/hero/coast-hero.webp",
  "palms-beach": "/assets/origin/palms-beach.webp",
  "palms-clouds": "/assets/origin/palms-clouds.webp",
  "copra-split": "/assets/products/copra-split.webp",
  "copra-hands": "/assets/products/copra-hands.webp",
  "copra-table": "/assets/products/copra-table.webp",
  "shell-texture": "/assets/products/shell-texture.webp",
  "charcoal-fire": "/assets/products/charcoal-fire.webp",
  "embers-close": "/assets/products/embers-close.webp",
  "briquettes-grill": "/assets/products/briquettes-grill.webp",
  "charcoal-dark": "/assets/products/charcoal-dark.webp",
  "oil-bottle": "/assets/products/oil-bottle.webp",
  "vco-bottle": "/assets/products/vco-bottle.webp",
  "white-copra": "/assets/products/white-copra.webp",
  "coconut-charcoal": "/assets/products/coconut-charcoal.webp",
  "coconut-briquettes": "/assets/products/coconut-briquettes.webp",
  "coconut-oil": "/assets/products/coconut-oil.webp",
  "coconut-vco": "/assets/products/coconut-vco.webp",
  "grove-fruit": "/assets/process/grove-fruit.webp",
  "select-coconut": "/assets/process/select-coconut.webp",
  "kiln-embers": "/assets/process/kiln-embers.webp",
  "sack-burlap": "/assets/process/sack-burlap.webp",
  "sacks-pile": "/assets/process/sacks-pile.webp",
  "port-cranes": "/assets/process/port-cranes.webp",
  "port-ship": "/assets/process/port-ship.webp",
  "harvest-piles": "/assets/process/harvest-piles.webp",
  "sort-yard": "/assets/process/sort-yard.webp",
  "split-fresh": "/assets/process/split-fresh.webp",
  "dry-house": "/assets/process/dry-house.webp",
  "control-kernel": "/assets/process/control-kernel.webp",
  "pack-sack": "/assets/process/pack-sack.webp",
  "deliver-barge": "/assets/process/deliver-barge.webp",
  "team-grove": "/assets/story/team-grove.webp",
  "learning-center": "/assets/story/learning-center.webp",
  "team-discussion": "/assets/story/team-discussion.webp",
  "field-visit": "/assets/story/field-visit.webp",
} as const;

export type AssetKey = keyof typeof ASSETS;
